# Functions generated by Clang.jl
include("./C/libhsl_mc78.jl")

function mc78_default_control(control) where T
  (T == Int32) && mc78_default_control_i(control)
  (T == Int64) && mc78_default_control_l(control)
end

function mc78_analyse_asm(n, ptr, row, perm, nnodes, sptr, sparent, rptr, rlist, control, stat,) where T
  (T == Int32) && mc78_analyse_asm_i(n, ptr, row, perm, nnodes, sptr, sparent, rptr, rlist, control, stat,)
  (T == Int64) && mc78_analyse_asm_l(n, ptr, row, perm, nnodes, sptr, sparent, rptr, rlist, control, stat,)
end

function mc78_analyse_elt(n, nelt, starts, vars, perm, eparent, nnodes, sptr, sparent, rptr,) where T
  (T == Int32) && mc78_analyse_elt_i(n, nelt, starts, vars, perm, eparent, nnodes, sptr, sparent, rptr,)
  (T == Int64) && mc78_analyse_elt_l(n, nelt, starts, vars, perm, eparent, nnodes, sptr, sparent, rptr,)
end

function mc78_supervars(n, ptr, row, perm, invp, nsvar, svar) where T
  (T == Int32) && mc78_supervars_i(n, ptr, row, perm, invp, nsvar, svar)
  (T == Int64) && mc78_supervars_l(n, ptr, row, perm, invp, nsvar, svar)
end

function mc78_compress_by_svar(n, ptr, row, invp, nsvar, svar, ptr2, lrow2, row2, st) where T
  (T == Int32) && mc78_compress_by_svar_i(n, ptr, row, invp, nsvar, svar, ptr2, lrow2, row2, st)
  (T == Int64) && mc78_compress_by_svar_l(n, ptr, row, invp, nsvar, svar, ptr2, lrow2, row2, st)
end

function mc78_etree(n, ptr, row, perm, invp, parent) where T
  (T == Int32) && mc78_etree_i(n, ptr, row, perm, invp, parent)
  (T == Int64) && mc78_etree_l(n, ptr, row, perm, invp, parent)
end

function mc78_elt_equiv_etree(n, nelt, starts, vars, perm, invp, nsvar, svar, ptr, row, eparent,) where T
  (T == Int32) && mc78_elt_equiv_etree_i(n, nelt, starts, vars, perm, invp, nsvar, svar, ptr, row, eparent,)
  (T == Int64) && mc78_elt_equiv_etree_l(n, nelt, starts, vars, perm, invp, nsvar, svar, ptr, row, eparent,)
end

function mc78_postorder(n, realn, ptr, perm, invp, parent, block_pivots) where T
  (T == Int32) && mc78_postorder_i(n, realn, ptr, perm, invp, parent, block_pivots)
  (T == Int64) && mc78_postorder_l(n, realn, ptr, perm, invp, parent, block_pivots)
end

function mc78_col_counts(n, ptr, row, perm, invp, parent, cc, wt) where T
  (T == Int32) && mc78_col_counts_i(n, ptr, row, perm, invp, parent, cc, wt)
  (T == Int64) && mc78_col_counts_l(n, ptr, row, perm, invp, parent, cc, wt)
end

function mc78_supernodes(n, realn, parent, cc, sperm, nnodes, sptr, sparent, scc, invp, control,) where T
  (T == Int32) && mc78_supernodes_i(n, realn, parent, cc, sperm, nnodes, sptr, sparent, scc, invp, control,)
  (T == Int64) && mc78_supernodes_l(n, realn, parent, cc, sperm, nnodes, sptr, sparent, scc, invp, control,)
end

function mc78_stats(nnodes, sptr, scc, nfact, nflops) where T
  (T == Int32) && mc78_stats_i(nnodes, sptr, scc, nfact, nflops)
  (T == Int64) && mc78_stats_l(nnodes, sptr, scc, nfact, nflops)
end

function mc78_row_lists_svar(args...) where T
  (T == Int32) && mc78_row_lists_svar_i(args...)
  (T == Int64) && mc78_row_lists_svar_l(args...)
end

function mc78_optimize_locality(n, realn, perm, invp, nnodes, sptr, sparent, rptr, rlist, sort) where T
  (T == Int32) && mc78_optimize_locality_i(n, realn, perm, invp, nnodes, sptr, sparent, rptr, rlist, sort)
  (T == Int64) && mc78_optimize_locality_l(n, realn, perm, invp, nnodes, sptr, sparent, rptr, rlist, sort)
end
