# Functions generated by Clang.jl
include("./C/libhsl_mc79.jl")

function mc79_default_control(control) where T
  (T == Int32) && mc79_default_control_i(control)
end

function mc79_matching(m, n, ptr, row, rowmatch, colmatch, control, info) where T
  (T == Int32) && mc79_matching_i(m, n, ptr, row, rowmatch, colmatch, control, info)
end

function mc79_coarse(m, n, ptr, row, rowperm, colperm, control, info) where T
  (T == Int32) && mc79_coarse_i(m, n, ptr, row, rowperm, colperm, control, info)
end

function mc79_fine(m, n, ptr, row, rowperm, colperm, rowcomp, colcomp, control, info) where T
  (T == Int32) && mc79_fine_i(m, n, ptr, row, rowperm, colperm, rowcomp, colcomp, control, info)
end
