# Functions generated by Clang.jl
include("./C/libhsl_mi20.jl")

function mi20_default_control(control) where T
  (T == Float32) && mi20_default_control_s(control)
  (T == Float64) && mi20_default_control_d(control)
end

function mi20_default_solve_control(solve_control) where T
  (T == Float32) && mi20_default_solve_control_s(solve_control)
  (T == Float64) && mi20_default_solve_control_d(solve_control)
end

function mi20_setup(n, ne, row, col, val, keep, control, info) where T
  (T == Float32) && mi20_setup_s(n, ne, row, col, val, keep, control, info)
  (T == Float64) && mi20_setup_d(n, ne, row, col, val, keep, control, info)
end

function mi20_setup_csr(n, ptr, col, val, keep, control, info) where T
  (T == Float32) && mi20_setup_csr_s(n, ptr, col, val, keep, control, info)
  (T == Float64) && mi20_setup_csr_d(n, ptr, col, val, keep, control, info)
end

function mi20_setup_csc(n, ptr, row, val, keep, control, info) where T
  (T == Float32) && mi20_setup_csc_s(n, ptr, row, val, keep, control, info)
  (T == Float64) && mi20_setup_csc_d(n, ptr, row, val, keep, control, info)
end

function mi20_setup_coord(n, ne, row, col, val, keep, control, info) where T
  (T == Float32) && mi20_setup_coord_s(n, ne, row, col, val, keep, control, info)
  (T == Float64) && mi20_setup_coord_d(n, ne, row, col, val, keep, control, info)
end

function mi20_finalize(keep, control, info) where T
  (T == Float32) && mi20_finalize_s(keep, control, info)
  (T == Float64) && mi20_finalize_d(keep, control, info)
end

function mi20_precondition(rhs, solution, keep, control, info) where T
  (T == Float32) && mi20_precondition_s(rhs, solution, keep, control, info)
  (T == Float64) && mi20_precondition_d(rhs, solution, keep, control, info)
end

function mi20_solve(rhs, solution, keep, control, solve_control, info) where T
  (T == Float32) && mi20_solve_s(rhs, solution, keep, control, solve_control, info)
  (T == Float64) && mi20_solve_d(rhs, solution, keep, control, solve_control, info)
end

function mi20_finalise(keep, control, info) where T
  (T == Float32) && mi20_finalize(keep, control, info)
  (T == Float64) && mi20_finalize(keep, control, info)
end
