# Functions generated by Clang.jl
include("./C/libhsl_mc64.jl")

function mc64_default_control(control) where T
  (T == Float32) && mc64_default_control_s(control)
  (T == Float64) && mc64_default_control_d(control)
  (T == ComplexF32) && mc64_default_control_c(control)
  (T == ComplexF64) && mc64_default_control_z(control)
end

function mc64_matching(job, matrix_type, m, n, ptr, row, cval, control, info, perm, scale) where T
  (T == Float32) && mc64_matching_s(job, matrix_type, m, n, ptr, row, cval, control, info, perm, scale)
  (T == Float64) && mc64_matching_d(job, matrix_type, m, n, ptr, row, cval, control, info, perm, scale)
  (T == ComplexF32) && mc64_matching_c(job, matrix_type, m, n, ptr, row, cval, control, info, perm, scale)
  (T == ComplexF64) && mc64_matching_z(job, matrix_type, m, n, ptr, row, cval, control, info, perm, scale)
end
