# Functions generated by Clang.jl
include("./C/libhsl_ma87.jl")

function ma87_default_control(control) where T
  (T == Float32) && ma87_default_control_s(control)
  (T == Float64) && ma87_default_control_d(control)
  (T == ComplexF32) && ma87_default_control_c(control)
  (T == ComplexF64) && ma87_default_control_z(control)
end

function ma87_analyse(n, ptr, row, order, keep, control, info) where T
  (T == Float32) && ma87_analyse_s(n, ptr, row, order, keep, control, info)
  (T == Float64) && ma87_analyse_d(n, ptr, row, order, keep, control, info)
  (T == ComplexF32) && ma87_analyse_c(n, ptr, row, order, keep, control, info)
  (T == ComplexF64) && ma87_analyse_z(n, ptr, row, order, keep, control, info)
end

function ma87_factor(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x) where T
  (T == Float32) && ma87_factor_s(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == Float64) && ma87_factor_d(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == ComplexF32) && ma87_factor_c(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == ComplexF64) && ma87_factor_z(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
end

function ma87_factor_solve(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x) where T
  (T == Float32) && ma87_factor_solve_s(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == Float64) && ma87_factor_solve_d(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == ComplexF32) && ma87_factor_solve_c(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
  (T == ComplexF64) && ma87_factor_solve_z(n, ptr, row, val, order, keep, control, info, nrhs, ldx, x)
end

function ma87_solve(job, nrhs, ldx, x, order, keep, control, info) where T
  (T == Float32) && ma87_solve_s(job, nrhs, ldx, x, order, keep, control, info)
  (T == Float64) && ma87_solve_d(job, nrhs, ldx, x, order, keep, control, info)
  (T == ComplexF32) && ma87_solve_c(job, nrhs, ldx, x, order, keep, control, info)
  (T == ComplexF64) && ma87_solve_z(job, nrhs, ldx, x, order, keep, control, info)
end

function ma87_sparse_fwd_solve(nbi, bindex, b, order, invp, nxi, index, x, w, keep, control, info) where T
  (T == Float32) && ma87_sparse_fwd_solve_s(nbi, bindex, b, order, invp, nxi, index, x, w, keep, control, info)
  (T == Float64) && ma87_sparse_fwd_solve_d(nbi, bindex, b, order, invp, nxi, index, x, w, keep, control, info)
  (T == ComplexF32) && ma87_sparse_fwd_solve_c(nbi, bindex, b, order, invp, nxi, index, x, w, keep, control, info)
  (T == ComplexF64) && ma87_sparse_fwd_solve_z(nbi, bindex, b, order, invp, nxi, index, x, w, keep, control, info)
end

function ma87_finalise(keep, control) where T
  (T == Float32) && ma87_finalise_s(keep, control)
  (T == Float64) && ma87_finalise_d(keep, control)
  (T == ComplexF32) && ma87_finalise_c(keep, control)
  (T == ComplexF64) && ma87_finalise_z(keep, control)
end

function ma87_finalize(keep, control) where T
  (T == Float32) && ma87_finalise(keep, control)
  (T == Float64) && ma87_finalise(keep, control)
  (T == ComplexF32) && ma87_finalise(keep, control)
  (T == ComplexF64) && ma87_finalise(keep, control)
end
