# Functions generated by Clang.jl
include("./C/libhsl_mc69.jl")

function mc69_verify(unit, type, findex, m, n, ptr, row, val, more) where T
  (T == Float32) && mc69_verify_s(unit, type, findex, m, n, ptr, row, val, more)
  (T == Float64) && mc69_verify_d(unit, type, findex, m, n, ptr, row, val, more)
  (T == ComplexF32) && mc69_verify_c(unit, type, findex, m, n, ptr, row, val, more)
  (T == ComplexF64) && mc69_verify_z(unit, type, findex, m, n, ptr, row, val, more)
end

function mc69_print(unit, lines, type, findex, m, n, ptr, row, val) where T
  (T == Float32) && mc69_print_s(unit, lines, type, findex, m, n, ptr, row, val)
  (T == Float64) && mc69_print_d(unit, lines, type, findex, m, n, ptr, row, val)
  (T == ComplexF32) && mc69_print_c(unit, lines, type, findex, m, n, ptr, row, val)
  (T == ComplexF64) && mc69_print_z(unit, lines, type, findex, m, n, ptr, row, val)
end

function mc69_set_values(type, lmap, map, val_in, ne, val_out) where T
  (T == Float32) && mc69_set_values_s(type, lmap, map, val_in, ne, val_out)
  (T == Float64) && mc69_set_values_d(type, lmap, map, val_in, ne, val_out)
  (T == ComplexF32) && mc69_set_values_c(type, lmap, map, val_in, ne, val_out)
  (T == ComplexF64) && mc69_set_values_z(type, lmap, map, val_in, ne, val_out)
end

function mc69_cscl_clean(unit, type, findex, m, n, ptr, row, val, noor, ndup, lmap, map) where T
  (T == Float32) && mc69_cscl_clean_s(unit, type, findex, m, n, ptr, row, val, noor, ndup, lmap, map)
  (T == Float64) && mc69_cscl_clean_d(unit, type, findex, m, n, ptr, row, val, noor, ndup, lmap, map)
  (T == ComplexF32) && mc69_cscl_clean_c(unit, type, findex, m, n, ptr, row, val, noor, ndup, lmap, map)
  (T == ComplexF64) && mc69_cscl_clean_z(unit, type, findex, m, n, ptr, row, val, noor, ndup, lmap, map)
end

function mc69_cscl_convert(unit, type, findex, m, n, ptr_in, row_in, val_in, ptr_out, lrow,) where T
  (T == Float32) && mc69_cscl_convert_s(unit, type, findex, m, n, ptr_in, row_in, val_in, ptr_out, lrow,)
  (T == Float64) && mc69_cscl_convert_d(unit, type, findex, m, n, ptr_in, row_in, val_in, ptr_out, lrow,)
  (T == ComplexF32) && mc69_cscl_convert_c(unit, type, findex, m, n, ptr_in, row_in, val_in, ptr_out, lrow,)
  (T == ComplexF64) && mc69_cscl_convert_z(unit, type, findex, m, n, ptr_in, row_in, val_in, ptr_out, lrow,)
end

function mc69_cscu_convert(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,) where T
  (T == Float32) && mc69_cscu_convert_s(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == Float64) && mc69_cscu_convert_d(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF32) && mc69_cscu_convert_c(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF64) && mc69_cscu_convert_z(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
end

function mc69_csclu_convert(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,) where T
  (T == Float32) && mc69_csclu_convert_s(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == Float64) && mc69_csclu_convert_d(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF32) && mc69_csclu_convert_c(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF64) && mc69_csclu_convert_z(unit, type, findex, n, ptr_in, row_in, val_in, ptr_out, lrow, row_out,)
end

function mc69_csrl_convert(unit, type, findex, m, n, ptr_in, col_in, val_in, ptr_out, lrow,) where T
  (T == Float32) && mc69_csrl_convert_s(unit, type, findex, m, n, ptr_in, col_in, val_in, ptr_out, lrow,)
  (T == Float64) && mc69_csrl_convert_d(unit, type, findex, m, n, ptr_in, col_in, val_in, ptr_out, lrow,)
  (T == ComplexF32) && mc69_csrl_convert_c(unit, type, findex, m, n, ptr_in, col_in, val_in, ptr_out, lrow,)
  (T == ComplexF64) && mc69_csrl_convert_z(unit, type, findex, m, n, ptr_in, col_in, val_in, ptr_out, lrow,)
end

function mc69_csru_convert(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,) where T
  (T == Float32) && mc69_csru_convert_s(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == Float64) && mc69_csru_convert_d(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF32) && mc69_csru_convert_c(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF64) && mc69_csru_convert_z(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
end

function mc69_csrlu_convert(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,) where T
  (T == Float32) && mc69_csrlu_convert_s(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == Float64) && mc69_csrlu_convert_d(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF32) && mc69_csrlu_convert_c(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
  (T == ComplexF64) && mc69_csrlu_convert_z(unit, type, findex, n, ptr_in, col_in, val_in, ptr_out, lrow, row_out,)
end

function mc69_coord_convert(unit, type, findex, m, n, ne, row_in, col_in, val_in, ptr_out, lrow,) where T
  (T == Float32) && mc69_coord_convert_s(unit, type, findex, m, n, ne, row_in, col_in, val_in, ptr_out, lrow,)
  (T == Float64) && mc69_coord_convert_d(unit, type, findex, m, n, ne, row_in, col_in, val_in, ptr_out, lrow,)
  (T == ComplexF32) && mc69_coord_convert_c(unit, type, findex, m, n, ne, row_in, col_in, val_in, ptr_out, lrow,)
  (T == ComplexF64) && mc69_coord_convert_z(unit, type, findex, m, n, ne, row_in, col_in, val_in, ptr_out, lrow,)
end
