# Functions generated by Clang.jl
include("./C/libhsl_mc68.jl")

function mc68_default_control(control) where T
  (T == Int32) && mc68_default_control_i(control)
end

function mc68_order(ord, n, ptr, row, perm, control, info) where T
  (T == Int32) && mc68_order_i(ord, n, ptr, row, perm, control, info)
end
