# Functions generated by Clang.jl
include("./C/libhsl_ma48.jl")

function ma48_initialize(factors) where T
  (T == Float32) && ma48_initialize_s(factors)
  (T == Float64) && ma48_initialize_d(factors)
end

function ma48_default_control(control) where T
  (T == Float32) && ma48_default_control_s(control)
  (T == Float64) && ma48_default_control_d(control)
end

function ma48_analyse(m, n, ne, row, col, val, factors, control, ainfo, finfo, perm, endcol) where T
  (T == Float32) && ma48_analyse_s(m, n, ne, row, col, val, factors, control, ainfo, finfo, perm, endcol)
  (T == Float64) && ma48_analyse_d(m, n, ne, row, col, val, factors, control, ainfo, finfo, perm, endcol)
end

function ma48_get_perm(args...) where T
  (T == Float32) && ma48_get_perm_s(args...)
  (T == Float64) && ma48_get_perm_d(args...)
end

function ma48_factorize(m, n, ne, row, col, val, factors, control, finfo, fast, partial) where T
  (T == Float32) && ma48_factorize_s(m, n, ne, row, col, val, factors, control, finfo, fast, partial)
  (T == Float64) && ma48_factorize_d(m, n, ne, row, col, val, factors, control, finfo, fast, partial)
end

function ma48_solve(m, n, ne, row, col, val, factors, rhs, x, control, sinfo, trans, resid, error) where T
  (T == Float32) && ma48_solve_s(m, n, ne, row, col, val, factors, rhs, x, control, sinfo, trans, resid, error)
  (T == Float64) && ma48_solve_d(m, n, ne, row, col, val, factors, rhs, x, control, sinfo, trans, resid, error)
end

function ma48_finalize(factors, control) where T
  (T == Float32) && ma48_finalize_s(factors, control)
  (T == Float64) && ma48_finalize_d(factors, control)
end

function ma48_special_rows_and_cols(factors, rank, rows, cols, control) where T
  (T == Float32) && ma48_special_rows_and_cols_s(factors, rank, rows, cols, control)
  (T == Float64) && ma48_special_rows_and_cols_d(factors, rank, rows, cols, control)
end

function ma48_determinant(factors, sgndet, logdet, control) where T
  (T == Float32) && ma48_determinant_s(factors, sgndet, logdet, control)
  (T == Float64) && ma48_determinant_d(factors, sgndet, logdet, control)
end

function ma48_finalise(factors, control) where T
  (T == Float32) && ma48_finalize(factors, control)
  (T == Float64) && ma48_finalize(factors, control)
end
