# Functions generated by Clang.jl
include("./C/libhsl_ma86.jl")

function ma86_default_control(control) where T
  (T == Float32) && ma86_default_control_s(control)
  (T == Float64) && ma86_default_control_d(control)
  (T == ComplexF32) && ma86_default_control_c(control)
  (T == ComplexF64) && ma86_default_control_z(control)
end

function ma86_analyse(n, ptr, row, order, keep, control, info) where T
  (T == Float32) && ma86_analyse_s(n, ptr, row, order, keep, control, info)
  (T == Float64) && ma86_analyse_d(n, ptr, row, order, keep, control, info)
  (T == ComplexF32) && ma86_analyse_c(n, ptr, row, order, keep, control, info)
  (T == ComplexF64) && ma86_analyse_z(n, ptr, row, order, keep, control, info)
end

function ma86_factor(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,) where T
  (T == Float32) && ma86_factor_s(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == Float64) && ma86_factor_d(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == ComplexF32) && ma86_factor_c(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == ComplexF64) && ma86_factor_z(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
end

function ma86_factor_solve(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,) where T
  (T == Float32) && ma86_factor_solve_s(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == Float64) && ma86_factor_solve_d(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == ComplexF32) && ma86_factor_solve_c(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
  (T == ComplexF64) && ma86_factor_solve_z(matrix_type, n, ptr, row, val, order, keep, control, info, nrhs, ldx,)
end

function ma86_solve(job, nrhs, ldx, x, order, keep, control, info, scale) where T
  (T == Float32) && ma86_solve_s(job, nrhs, ldx, x, order, keep, control, info, scale)
  (T == Float64) && ma86_solve_d(job, nrhs, ldx, x, order, keep, control, info, scale)
  (T == ComplexF32) && ma86_solve_c(job, nrhs, ldx, x, order, keep, control, info, scale)
  (T == ComplexF64) && ma86_solve_z(job, nrhs, ldx, x, order, keep, control, info, scale)
end

function ma86_finalise(keep, control) where T
  (T == Float32) && ma86_finalise_s(keep, control)
  (T == Float64) && ma86_finalise_d(keep, control)
  (T == ComplexF32) && ma86_finalise_c(keep, control)
  (T == ComplexF64) && ma86_finalise_z(keep, control)
end

function ma86_finalize(keep, control) where T
  (T == Float32) && ma86_finalise(keep, control)
  (T == Float64) && ma86_finalise(keep, control)
  (T == ComplexF32) && ma86_finalise(keep, control)
  (T == ComplexF64) && ma86_finalise(keep, control)
end
